# Generated by Django 4.0.4 on 2022-04-20 07:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('depart', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('altitude_depart', models.IntegerField(verbose_name='Altitude (en m)')),
                ('altitude_min', models.IntegerField(verbose_name='Altitude minimum (en m)')),
                ('altitude_max', models.IntegerField(verbose_name='Altitude maximum (en m)')),
                ('denivele_pos', models.IntegerField(verbose_name='Dénivelé positif cumulé (en m')),
                ('denivele_neg', models.IntegerField(verbose_name='Dénivelé négatif cumulé (en m')),
                ('duree_estimee', models.FloatField(verbose_name='Durée estimée (en h)')),
                ('difficulte_estimee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté estimée (de 1 à 5)')),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_reelle', models.FloatField(verbose_name='Durée réelle (en h)')),
                ('nb_personne', models.IntegerField(verbose_name='Nombre de personnes ayant participé à la sortie')),
                ('niveaux', models.CharField(choices=[('0', 'Tous débutants'), ('1', 'Mixte'), ('2', 'Tous experts')], max_length=32, verbose_name='Niveau des personnes')),
                ('meteo', models.CharField(choices=[('0', 'Bonne météo'), ('1', 'Météo moyenne'), ('2', 'Mauvaise météo')], max_length=32, verbose_name='Météo')),
                ('difficulte_reelle', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté ressentie (de 1 à 5)')),
                ('date_de_sortie', models.DateField(verbose_name='Date de sortie')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
