# Generated by Django 4.0.4 on 2022-04-21 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_depart',
            field=models.PositiveIntegerField(verbose_name='Altitude (en m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_max',
            field=models.PositiveIntegerField(verbose_name='Altitude maximum (en m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='altitude_min',
            field=models.PositiveIntegerField(verbose_name='Altitude minimum (en m)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_neg',
            field=models.PositiveIntegerField(verbose_name='Dénivelé négatif cumulé (en m'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='denivele_pos',
            field=models.PositiveIntegerField(verbose_name='Dénivelé positif cumulé (en m'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='difficulte_estimee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté estimée (de 1 à 5)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='duree_estimee',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durée estimée (en h)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='duree_reelle',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durée réelle (en h)'),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='nb_personne',
            field=models.PositiveIntegerField(verbose_name='Nombre de personnes ayant participé à la sortie'),
        ),
    ]
